### ISSUE TITLE
Would Love to have this option to run this as pkg

### ISSUE THREAD

**Issue by bersky** [jake-b/RoutingMenu#1]
Hi Jake,

Fabulous stuff!!! my kid wanted me to do it over and over again!  Brilliant!  Thanks so much for releasing this.  And your your presentation today.  Awesome work!  

Is there a way to make this an executable, stand alone package to run outside of Xcode?  I'm not so familiar with Xcode, so I'm might have missed a make option,

cheers,
Mark

**Comment by jake-b** [comment]
Thanks for the kind words.

After running, look in the source list on the left side for "Products".  You should see the app.  Right click and "Show in Finder".  

Good luck!

**Comment by bersky** [comment]
Awesome!!!

Yes that’s great love it!

Mark
